# Generated by Django 4.2.1 on 2023-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
